services:
  api:
    build: .
    image: fastapi-train:local
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./app:/code/app
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment: {WATCHFILES_FORCE_POLLING: "true"}